### ISSUE TITLE
 [Question] Ho do install the files on correctly on the robot?

### ISSUE THREAD

**Issue by jaddel** [johnDorian/rockbin#14]
thank you for the great work it sound pretty neat! 

I'm not that familiar with all this. Could leave a few instructions how to install the rockbin in the first place?

**Comment by pkishino** [comment]
scp the files to the robot,
then follow this:
https://github.com/johnDorian/rockbin#setting-it-up-as-an-upstart-service
and look at the
https://github.com/johnDorian/rockbin#install
to test/run it..very easy

**Comment by jaddel** [comment]
thx

**Comment by jaddel** [comment]
solution supplied
