### ISSUE TITLE
Issues with RC `configure` command

### ISSUE THREAD

**Issue by corbanmailloux** [johnDorian/rockbin#16]
Hey. I just wanted to provide some feedback on the new RC release: https://github.com/johnDorian/rockbin/releases/tag/v0.2.0-rc

I love the `configure` command. It made the initial setup that much easier. I ran into a few issues with it:

* On my system, It seems that the `configure` command did set up the init file, but it didn't mark the `S12Rockbin` file as executable so the init script wasn't running.
* When I got it running, I was seeing errors because `sudo` wasn't available on my vacuum. Removing the `sudo` calls worked for the most part and I was able to start the service.
* The `is_running` helper in the file doesn't seem to run correctly because `ps` on my install doesn't support the `-p` option.

I'm not sure if this is due to differences in my setup/vacuum vs. yours, but I'm running a Roborock S5, with Valetudo 2021.11.0, with a setup built by [DustBuilder](https://builder.dontvacuum.me/_s5.html) with the option to install nano, wget, etc.

Looks like my BusyBox shell is:
```
BusyBox v1.24.1 (2019-11-15 15:22:50 CST) multi-call binary.
```

Thanks for the work on this tool!

**Comment by johnDorian** [comment]
Thanks for testing and the feedback. Any chance you could give provide the following information:

- Does the `get_pid` function work?
- When the app is running, could you see if a folder within the /proc directory is created for the corresponding PID. I'm hoping `/proc/{PID}/status` exists.

If both of those things are working than we could modify `is_running` to the following: 
```bash
is_running() {
    [ -f "$pid_file" ] && [ -e /proc/$(get_pid)/status ] > /dev/null 2>&1
}
```

It would be great if you could also test the above `is_running` cmd as well.

**Comment by corbanmailloux** [comment]
* `get_pid` does appear to work correctly, returning the PID from `/var/run/S12Rockbin.pid`.
* With the app running on PID `369`, I do not have a `/proc/369` directory.
* Because the proc directory is missing, the `is_running` function you shared won't find the file and it returns a status code of `1`.

**Comment by corbanmailloux** [comment]
I'm also having some trouble getting the tool to stay running reliably. It seems that the job is failing on an unexpected network error, causing the process to quit.
For reference, here's the error I'm occasionally getting:
```
time="2021-11-21T11:28:36Z" level=fatal msg="Network Error : dial tcp 10.0.0.253:1883: connect: network is unreachable"
```
(That IP:port is accurate for my MQTT server, and the connection normally functions as expected.)

**Comment by corbanmailloux** [comment]
I've been playing with the [new release](https://github.com/johnDorian/rockbin/releases/tag/v0.2.0-rc2) and it does seem that the `sudo` and `is_running` issues have been solved. 

On my install, it looks like the `S12Rockbin` init script is still not being marked as executable when running the `configure` command. 

Bigger concern is that is seems that I have managed to get the vacuum stuck during boot. The only changes I have made are making the init script executable, so I'm thinking that maybe some type of error in an init script is blocking startup. I'm not really sure how that would happen at the moment.

I'll have to factory reset the vacuum and try again to see if I can reproduce, but that will take some time so I figured I'd give you a heads up early in case you have an idea.

**Comment by corbanmailloux** [comment]
I factory reset my vacuum to clear it out, reinstalled Valetudo (mostly to root it and get SSH), and installed the RC2 release following these steps.

```bash
scp rockbin root@10.0.0.239:/root/rockbin
ssh root@10.0.0.239
chmod +x rockbin # Note: I think this command is in the wrong place in your release notes.
./rockbin configure
# Ran through the config...
chmod +x /etc/init/S12Rockbin # This seemed to be required for the init script to run.
mv rockbin /usr/local/bin/rockbin
reboot now
```

What I've found now is that something in these changes is causing the system to be unbootable. With the S5 at least, there are two system partitions (see the S5 section [here](https://valetudo.cloud/pages/general/upgrading.html)), so after the reboot I'm actually on partition `b` which has no Rockbin setup. Attempting to install Rockbin again on this partition causes both partitions to be unbootable, requiring a full factory reset. If I wait a while for the boot to fully fail, the power LED blinks rapid red, indicating a failure.

For reference, you can tell which partition you're on by running `grep "boot_fs" /proc/cmdline` and checking for `boot_fs=a` or `boot_fs=b`.


I'll perform another factory reset tomorrow and see if I can figure out what would be causing this. The previous RC release worked fine, and when I tried running the init files directly the service started as expected. Ex: `/etc/init/S12Rockbin start`. I also validated `status` and `stop`, both with expected results. 
Based on the [diffs](https://github.com/johnDorian/rockbin/compare/v0.2.0-rc...v0.2.0-rc2), I'll try making just the init file changes first and see if somehow that's the issue. I'm suspicious that the uptime check has a potential infinite loop which may hang the boot process, but that's just speculation.

(Sidenote: Let me know if you'd prefer these reports in a new issue or other method of communication. I just figured extra RC feedback would be helpful.)

**Comment by johnDorian** [comment]
Thanks for trying it out and sorry for the hassle. I assume the while loop with the sleep in the unit script is causing the issue. I’ll remove the loop and create a new release later today.

**Comment by johnDorian** [comment]
I deleted the old release and created a new one. 
Can you try running the app before restarting using `rockbin serve` . The other change since rc1 is a http server running on port 9999 by default. This may be causing your issue.

**Comment by corbanmailloux** [comment]
I've reset and tried out the latest release. The server starts normally using your `serve` example command.

I did still have to manually `chmod +x /etc/init/S12Rockbin`, as the `configure` step didn't mark it executable.
Good news! The init script is no longer failing the boot process of my vacuum, and it is properly triggering rockbin to start.

The bad news is that I am still getting the following error, likely because the network is still starting up:
```
time="1970-01-01T04:04:56Z" level=debug msg="Connecting to mqtt broker" mqtt_broker="10.0.0.253:1883"
time="2021-11-25T03:39:06Z" level=fatal msg="Network Error : dial tcp 10.0.0.253:1883: connect: network is unreachable"
```
If I start the service manually (`/etc/init/S12Rockbin start`) after boot, the service comes up without error.

Would it be possible to add a couple retries for network errors in the code?

**Comment by johnDorian** [comment]
I've added a backoff retry method for the mqtt connection. Not sure how this will play with the robot during boot, but maybe it will help. 

The only last issue is the file permissions for the `/etc/init/S12Rockbin`. Can you provide me with the file permissions of what the rockbin app creates for the file `ls -ltr /etc/init/S12Rockbin` and what the output is after your chmod +x modification.

**Comment by corbanmailloux** [comment]
### Connection Error
With the new release, it seems the startup connection issues have been solved! Thank you.
Just for reference, here's the debug log when starting up, with a 60 second total MQTT connection retry configuration.
```
time="1970-01-04T03:03:08Z" level=info msg="Starting rockbin service"
time="1970-01-04T03:03:08Z" level=debug msg="Setup logger with log level" loglevel=debug
time="2021-11-28T02:37:15Z" level=debug msg="mqtt connection attempt failed. Trying again in 1.104660288s"
time="2021-11-28T02:37:20Z" level=debug msg="mqtt connection attempt failed. Trying again in 2.160763633s"
time="2021-11-28T02:37:22Z" level=info msg="Connected to mqtt broker" mqtt_broker="10.0.0.253:1883"
```

### Permissions Issue
I deleted `/etc/init/S12Rockbin` before running `configure` to start from a clean place. After running `configure` with the rc5 release, here are the permissions:
```
-rw-r--r--    1 root     root          2076 Nov 28 02:33 /etc/init/S12Rockbin
```

Then after `chmod +x /etc/init/S12Rockbin`, it's:
```
-rwxr-xr-x    1 root     root          2076 Nov 28 02:33 /etc/init/S12Rockbin
```

Assuming this can be fixed by the configure script, that'd be great. But I also think this is a reasonable step to do manually if you add it to the install instructions.

Thank you for your work on this.
