### ISSUE TITLE
initctl: command not found

### ISSUE THREAD

**Issue by jokerigno** [johnDorian/rockbin#5]
Hi,

I followed istruction on readme page but I cannot put rockbin to work on startup.

this is the error I see when I launch _initctl reload-configuration_

`-bash: initctl: command not found`

I run Valetudo-RE version 0.9.8.1 with firmware 2008

**Comment by johnDorian** [comment]
Hey, 
Did you try `sudo reboot now`. I'm using an older firmware, but I have tested using just this to add the new service. 

Do you have any logs in `/var/log/upstart/rockbin.log`?

**Comment by jokerigno** [comment]
Uhm I rebooted and then run this command:

MQTT_USERNAME=xxxxxxxxxMQTT_PASSWORD='xxxxxxxxxxxxxxxx' ./rockbin -mqtt_server mqtt://192.168.2.100:1883 -log_level debug


This is what I see on prompt:

INFO[2020-11-10T23:32:31Z] Starting rockbin service
DEBU[2020-11-10T23:32:31Z] Setup logger with log level                   loglevel=debug
DEBU[2020-11-10T23:32:31Z] Found mqtt username                           mqtt_username=jarvis
DEBU[2020-11-10T23:32:31Z] Found mqtt password
DEBU[2020-11-10T23:32:31Z] Connecting to mqtt broker                     mqtt_broker="192.168.2.100:1883"
INFO[2020-11-10T23:32:31Z] Connected to mqtt broker                      mqtt_broker="192.168.2.100:1883"
DEBU[2020-11-10T23:32:31Z] Sending mqtt config
DEBU[2020-11-10T23:32:31Z] Setting up file watcher

I searched for rockbin.log but there's no file in that folder.

**Comment by johnDorian** [comment]
Ok. Have you setup the `/etc/init/rockbin.conf` file on the vacuum? Can you provide the contents (minus the password) of your `/etc/init/rockbin.conf` file. 

If you don't already could you append `-log_level debug` and try rebooting the vacuum and see if you get any logs.

**Comment by Sennevds** [comment]
I have the same problem. Because of the newer firmware no initctl and restarting doesn't start the rockbin executable. Also no logging available. Here's my conf:
```conf
description     "rockbin mqtt publisher for the bin"
start on filesystem and net-device-up IFACE=wlan0
stop on runlevel [!2345]
respawn
umask 022
setuid root
setgid root
console log
env MQTT_USERNAME=*****
env MQTT_PASSWORD=*****
script
    exec /usr/local/bin/rockbin -mqtt_server mqtt://192.168.0.15:1883 -full_time 2400 -log_level debug
end script
```

**Comment by jokerigno** [comment]
YEs I do have setup config file.

Here's the text:

> description     "rockbin mqtt publisher for the bin"
> start on filesystem and net-device-up IFACE=wlan0
> stop on runlevel [!2345]
> respawn
> umask 022
> setuid root
> setgid root
> console log
> # If you have special characters in your password use single quotes ' or escape the special characters in your passowrd
> # env MQTT_USERNAME=jarvis
> # env MQTT_PASSWORD='xxxxxxxxxxxxxx'
> script 
>     exec /usr/local/bin/rockbin -mqtt_server mqtt://192.168.2.100:1883 -full_time 2400 -log_level debug
> end script

I rebooted then the vacuum via prompt using just reboot.

Looked at /var/log/upstart/ but i see only valetudo.log

I prompted manually 

>     exec /usr/local/bin/rockbin -mqtt_server mqtt://192.168.2.100:1883 -full_time 2400 -log_level debug

and I see previous messages plus new ones and the vacuumbin sensor has been created on my mqtt broker.

> root@rockrobo:~# exec /usr/local/bin/rockbin -mqtt_server mqtt://192.168.2.100:1                                                                                                                                                             883 -full_time 2400 -log_level debug
> INFO[2020-11-11T08:24:24Z] Starting rockbin service
> DEBU[2020-11-11T08:24:24Z] Setup logger with log level                   logleve                                                                                                                                                             l=debug
> DEBU[2020-11-11T08:24:24Z] Connecting to mqtt broker                     mqtt_br                                                                                                                                                             oker="192.168.2.100:1883"
> INFO[2020-11-11T08:24:24Z] Connected to mqtt broker                      mqtt_br                                                                                                                                                             oker="192.168.2.100:1883"
> DEBU[2020-11-11T08:24:24Z] Sending mqtt config
> DEBU[2020-11-11T08:24:24Z] Setting up file watcher
> DEBU[2020-11-11T08:25:24Z] Sending mqtt config
> INFO[2020-11-11T08:25:24Z] Parsed bin time                               bin_time=62106
> INFO[2020-11-11T08:25:24Z] Converted Value                               bin_time=62106 value=2587.75
> DEBU[2020-11-11T08:25:24Z] Sending mqtt message
> DEBU[2020-11-11T08:26:24Z] Sending mqtt config
> INFO[2020-11-11T08:26:24Z] Parsed bin time                               bin_time=62106
> INFO[2020-11-11T08:26:24Z] Converted Value                               bin_time=62106 value=2587.75
> DEBU[2020-11-11T08:26:24Z] Sending mqtt message
> DEBU[2020-11-11T08:27:24Z] Sending mqtt config
> INFO[2020-11-11T08:27:24Z] Parsed bin time                               bin_time=62106
> INFO[2020-11-11T08:27:24Z] Converted Value                               bin_time=62106 value=2587.75
> DEBU[2020-11-11T08:27:24Z] Sending mqtt message
> DEBU[2020-11-11T08:28:24Z] Sending mqtt config
> INFO[2020-11-11T08:28:24Z] Parsed bin time                               bin_time=62106
> INFO[2020-11-11T08:28:24Z] Converted Value                               bin_time=62106 value=2587.75
> DEBU[2020-11-11T08:28:24Z] Sending mqtt message

I run a cleaning session and the emptied the bin. The value did not change.

I had to rerun command in prompt to see value 0 for vacuum bin.

**Comment by Sennevds** [comment]
Looks like it was what I thought. The new fw doens't work with the conf files.
I've created a S12rockbin file in the /etc/init/ folder with following content:
```sh
#!/bin/sh

load() {
    curtime=`cat /proc/uptime | awk -F ' ' '{print $1}'`
    echo "[$curtime] start rockbin-daemon"
    start-stop-daemon -S -b -q -m -p /var/run/rockbin-daemon.pid -x /usr/local/bin/rockbin-daemon.sh
}

unload() {
    echo "stopping rockbin" >/dev/kmsg
    start-stop-daemon -K -q -p /var/run/rockbin-daemon.pid
    while killall rockbin; do sleep 1; done
}

status() {
    if [ ! -f /var/run/rockbin-daemon.pid -o -z "$(ps | grep `cat /var/run/rockbin-daemon.pid` | grep -v grep)" ]; then
        echo "rockbin seems stopped"
    else
        echo "rockbin seems started"
    fi
}

case "$1" in
    start)
        load
        ;;
    stop)
        unload
        ;;
    restart)
        unload
        load
        ;;
    status)
        status
        ;;
    *)
        echo "$0 <start/stop/restart/status>"
        ;;
esac
``` 
and created the /usr/local/bin/rockbin-daemon.sh file like this:
```sh
#!/bin/sh
# from https://github.com/zvldz/vacuum/commits/master/custom-script/files/valetudo-daemon.sh
# created by:  zvldz aka vtel


mkdir -p /var/log/upstart

while :; do
    sleep 5
    if [ `cut -d. -f1 /proc/uptime` -lt 300 ]; then
        echo -n "Waiting for 20 sec after boot..."
        sleep 20
        echo " done."
    fi

    pidof SysUpdate > /dev/null  2>&1
    if [ $? -ne 0 ]; then
    echo "Running Valetudo"
    MQTT_USERNAME=xxxx MQTT_PASSWORD=xxxx /usr/local/bin/rockbin -mqtt_server mqtt://192.168.0.15:1883 -full_time 2400 -log_level debug >> /var/log/upstart/rockbin.log 2>&1
    else
    echo "Waiting for SysUpdate to finish..."
    fi
done
```
Probably there needs to be some finetuning to both scripts because this is just a copy paste of the valetudo scripts and my Linux knowledge isn't that good.

**Comment by johnDorian** [comment]
Thanks a lot for this @Sennevds. Much appreciated. Looks like they are coming from here: https://github.com/zvldz/vacuum/tree/46ea4810d10e8b5bc4957c15e23981ebf708bbc9/custom-script/files

I'll look into a bit more, but feel free to open a PR for this. 

Thanks again

**Comment by Sennevds** [comment]
Indeed if you look at the following line https://github.com/zvldz/vacuum/blob/0a0d8e07a3da21431dd0d2b0cdc0a4c68c2fd642/custom-script/custom_valetudo.sh#L62 it depends if the inittab file is there or not. I was thinking about creating a pr but because I've just copied the original files and didn't checked all the lines what they are doing I just posted it here.

If I know what's really happening I will make a pr!

**Comment by johnDorian** [comment]
I just created a PR for this to solve this. I'm on an older firmware so I can't test it myself. It would be great if you could have a look at it @Sennevds and provide some feedback.

**Comment by Sennevds** [comment]
@johnDorian I wanted to make some changes but you've closed the PR and removed the branch

**Comment by johnDorian** [comment]
Yeah sorry about that. I’ll reopen it again later today. I decided against linking to the vacuum repo as it is licensed as GPL and I really don’t like that. 

I also think we can simplify it a little more than the two scripts.

**Comment by Sennevds** [comment]
Aha no problem. I've forked your repo and making some changes so you can give the mqtt username password and state topic as arguments

**Comment by jokerigno** [comment]
Hi all, any update on startup scripts for fw>2008?

**Comment by jokerigno** [comment]
No news about the merge?

**Comment by Sennevds** [comment]
> No news about the merge?

You could use the code above I've posted this works for me!

**Comment by jokerigno** [comment]
> You could use the code above I've posted this works for me!

Oh I tried. But It's not working. My rockbin service does not autostart at boot.


Here's my file copypasted starting from yours:

#!/bin/sh
# from https://github.com/zvldz/vacuum/commits/master/custom-script/files/valetudo-daemon.sh
# created by:  zvldz aka vtel


mkdir -p /var/log/upstart

while :; do
    sleep 5
    if [ `cut -d. -f1 /proc/uptime` -lt 300 ]; then
        echo -n "Waiting for 20 sec after boot..."
        sleep 20
        echo " done."
    fi

    pidof SysUpdate > /dev/null  2>&1
    if [ $? -ne 0 ]; then
    echo "Running Valetudo"
    MQTT_USERNAME=xxxxxxxxx MQTT_PASSWORD=xxxxxxxxxx /usr/local/bin/rockbin -mqtt_server mqtt://192.168.2.100:1883 -full_time 2400 -log_level debug >> /var/log/upstart/rockbin.log 2>&1
    else
    echo "Waiting for SysUpdate to finish..."
    fi
done

**Comment by Sennevds** [comment]
you need to create a new file in /etc/init/S12rockbin  with following content:

```
#!/bin/sh

###############################################
## This file is copied from https://raw.githubusercontent.com/zvldz/vacuum/46ea4810d10e8b5bc4957c15e23981ebf708bbc9/custom-script/files/S11valet$
## Several modifications (commented below) have been made to the original file.
###############################################


load() {
    curtime=`cat /proc/uptime | awk -F ' ' '{print $1}'`
    echo "[$curtime] start rockbin-daemon"
    start-stop-daemon -S -b -q -m -p /var/run/rockbin-daemon.pid -x /usr/local/bin/rockbin-daemon.sh
}

unload() {
    echo "stopping rockbin" >/dev/kmsg
    start-stop-daemon -K -q -p /var/run/rockbin-daemon.pid
    while killall rockbin 2>/dev/null; do sleep 1; done
}

status() {
    if [ ! -f /var/run/rockbin-daemon.pid -o -z "$(ps | grep `cat /var/run/rockbin-daemon.pid` | grep -v grep)" ]; then
        echo "rockbin seems stopped"
    else
        echo "rockbin seems started"
    fi
}

case "$1" in
    start)
        load
        ;;
    stop)
        unload
        ;;
    restart)
        unload
        load
        ;;
    status)
        status
        ;;
    *)
        echo "$0 <start/stop/restart/status>"
        ;;
esac
```

**Comment by jokerigno** [comment]
Sorry, I created it but doesn't clarify it.  I used your new code ( I saw you add some line, just to be sure). And then reboot via consolle. I started a cleaning session but no rockbin is created in my mqtt broker or in HA. 

I tried via console to send this message:

MQTT_USERNAME=xxx MQTT_PASSWORD=xxxxx /usr/local/bin/rockbin -mqtt_server mqtt://192.168.2.100:1883 -full_time 2400 but then again nothing happens.

All files are with 755 permission. I don't know how to make it work!

**Comment by jokerigno** [comment]
Update : my issue was related to the files. I recreated them using vi and then make them executible with chmod +x and reboot. Now service works as expected :)

I leave the issue open because I don't know if @johnDorian want to merge something or not.
